use_frameworks!

source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
source 'https://github.com/beedroid/koomee_RK_specs.git'

platform :ios, '9.0'

target 'RKTestModule_Example' do
  pod 'RKTestModule', :path => '../'
  pod 'RKBaseModule'
  pod 'SDWebImage', '4.2.3'
  pod 'CocoaLumberjack'
  # 列表空数据提示
  pod 'DZNEmptyDataSet'
  pod 'CocoaAsyncSocket'
  pod 'YogaKit', '~> 1.7'
  
  pod 'JLRoutes', '~> 2.0.1'
  pod 'JSONModel', '~> 1.7.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'AFNetworking'

#   相册
#  pod 'YBImageBrowser'
#  # 日历组件
#  pod 'PDTSimpleCalendar'
#  # 颜色框架
#  pod 'ChameleonFramework'
#  # appstore评分
#  pod 'iRate'
#  # GameCenter
#  pod 'GameCenterManager'
#  # 侧边栏
#  pod 'PKRevealController'
#  # 自定义的文本输入控件
#  pod 'SlackTextViewController'
#  # 提供很多种预先定义好的cell
#  pod 'RETableViewManager'
#  # 向用户获取设备权限提示
#  pod 'PermissionScope'
#  # HUD
#  pod 'SVProgressHUD'
#  # awesome font
#  pod 'FontAwesomeKit'
#  # cell滑动动画
#  pod 'MGSwipeTableCell'
#  # IAP
#  pod 'IAPHelper'
#  # APP内加载自定义字体
#  pod 'FontBlaster'
#  # 交叉推销，更多下载
#  pod 'TAPromotee'
#  # 大图加载，渐变动画
#  pod 'Concorde'
#  # keychain权限获取
#  pod 'KeychainAccess'
  
  target 'RKTestModule_Tests' do
    inherit! :search_paths

    
  end
end

